### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Avinar-24** [Avinar-24/telegram-graphs#7]
*The version numbers in this issue reflect version numbers of Kibana releases, at which we're planning to have the functionality implemented in Elastic charts. They are not reflecting actual Elastic Chart version numbers.*

# Kibana 7.1 

- [x] `DONE` Preparation for TSVB timeseries chart replacement #64 
    - [x] `DONE` Series specific styling (line width, opacity) #138 PR #170 
    - [x] `DONE` Handle band area charts (used on percentile band mode) #144 PR #157 
    - [x] `DONE` Add last bucket value on the legend #143 PR #155
    - [x] `DONE` Fix for time scales in different time zones #130 PR#151
    - [x] `DONE` Handle/Test negative values in stacked area charts  #135 PR #149 
    - [x] `DONE` Add annotation line #81 PR #126 
    - [x] `DONE` hide in legend (hide that series from the legend) #137 PR #147 
    - [x] `DONE` Add a separated name props on each series #136 PR #142
    - [x] `DONE` Display orphan data points on line/area series #63 PR #114
    - [x] `DONE` [Add external custom colour from spec props](#39) #39 PR #95
    - [x] `DONE` Crosshair and vertical/horizontal cursors #80 #58  PR #96
    - [x] `DONE` Scale data to specific domain #86 PR #98
    - [x] `DONE` Add filter in/out series only action to listeners) PR #51
    - [x] `DONE` Add hide/show series chart internals) PR #51
    - [x] `DONE` Add hover/click event for each legend series PR #51
    - [x] `DONE` Add color picker for each legend series #23 PR #51
- [ ] `IN PROGRESS` Replacement of the chart (support to EPAM) #108
- [ ] Preparation for Discovery chart replacement
    - [ ] Replacement of the chart
    - [ ] `IN PROGRESS` Add annotation rects #105 
- [ ] Value labels option for charts without hovering #67
    - [ ] Add text annotation capability (value labels will be a form of text annotation)
- [ ] Basic export as PNG function #82
- [ ] Visual regression tests #77
- [ ] Avoid clipping tooltip markers on edges #20
